version: '3.1'

networks:
    application:
        driver: bridge
volumes:
    mysql-data:
        driver: local

services:
    api:    
        build: 
            context: docker/    
        container_name: api
        depends_on:
          - mysql
        links:
          - mysql
        ports:
            - 8080:8080
        expose:
            - "9000"
            - "9001"      
        volumes:
            - .:/home/php/app
        networks:
            - application
    mysql:
        container_name: mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "MySql2019!"
            MYSQL_DATABASE: "api"
        ports:
            - "3306:3306"
        volumes:
            - /home/Volumes/MySql:/var/lib/mysql
        networks:
            - application